# Generated by Django 5.0.4 on 2024-04-10 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_litter', models.PositiveIntegerField(blank=True, null=True)),
                ('denominations', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l')], default=None, max_length=10)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productdetails')),
            ],
        ),
    ]
