# Generated by Django 5.0.4 on 2024-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
