# Generated by Django 5.0.4 on 2024-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
